name: Sort
run-name: Sort Text File
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Working directory'
        type: string
        default: '.'
        required: true

jobs:
  sort:
    name: Sort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Modify (${{ inputs.path }})
        run: |
          function getdir() {
            for file in $1/*; do
              if [ -f $file ]; then
                file=${file:2}
                if [[ $file = *.txt ]]; then
                  echo $file
                  sort -u $file -o $file
                fi
              else
                getdir $file
              fi
            done
          }
          getdir ${{ inputs.path }}
      - name: Commit & Push
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: 'Sort file'
